-- MySQL Script generated by MySQL Workbench
-- Tue 14 Nov 2017 09:27:30 AM MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eyedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eyedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eyedb` DEFAULT CHARACTER SET utf8 ;
USE `eyedb` ;

-- -----------------------------------------------------
-- Table `eyedb`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyedb`.`Devices` (
  `deviceID` INT NOT NULL,
  `deviceType` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `descr` VARCHAR(150) NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  `MAC` VARCHAR(17),
  PRIMARY KEY (`deviceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyedb`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyedb`.`Data` (
  `deviceID` INT NOT NULL,
  `timeRecieved` INT NOT NULL,
  `light` DOUBLE NULL,
  `motion` BOOLEAN NULL,
  `pressure` DOUBLE NULL,
  `temperature` DOUBLE NULL,
  `humidity` DOUBLE NULL,
  `co2` INT NULL,
  `button` BOOLEAN NULL,
  `altitude` DOUBLE NULL,
  `voc` INT NULL,
  `sound` INT NULL,
  `MAC` VARCHAR(17) NOT NULL,

  PRIMARY KEY (`MAC`,`timeRecieved`),
  CONSTRAINT `deviceID`
    FOREIGN KEY (`deviceID`)
    REFERENCES `eyedb`.`Devices` (`deviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyedb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyedb`.`Users` (
  `userID` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `salt` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyedb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyedb`.`Login` (
  `loginID` INT NOT NULL,
  `IP` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `action` VARCHAR(45) NULL,
  `locked` VARCHAR(45) NULL,
  PRIMARY KEY (`loginID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
